### ISSUE TITLE
Multiple image?

### ISSUE THREAD

**Issue by adamhongmy** [agustinslions/SLPhotoSelection#1]
Nice library and easy implementation. Just one request to have an array of images? :D

**Comment by agustinslions** [comment]
Thanks! Great recommendation! I will do it.

**Comment by agustinslions** [comment]
@adamhongmy I implemented your recommendation. Please check it and if you like make me more feedback! Thanks

**Comment by adamhongmy** [comment]
@agustinslions Hello! Thanks for the effort but I couldn't see any new codes. The last commit was 3 months ago. Am I missing something?

**Comment by agustinslions** [comment]
Hello! Now you can see the new codes. I forgot the most important things... merge :) .
