### ISSUE TITLE
Installation instruction...

### ISSUE THREAD

**Issue by iSpartak** [agustinslions/SLPhotoSelection#2]
You forgot to mention that 2 keys must be added in info.plist to use your lib: 

Photo :

Key    :  Privacy - Photo Library Usage Description    
Value  :  $(PRODUCT_NAME) photo use

Camera :

Key    :  Privacy - Camera Usage Description   
Value  :  $(PRODUCT_NAME) camera use

Otherwise app is crashing

**Comment by agustinslions** [comment]
@iSpartak Excellent! I add it now.
